'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});
var FORM_CONTROL_STATUS = exports.FORM_CONTROL_STATUS = {
  INDETERMINATE: 'FORM_CONTROL_STATUS.INDETERMINATE',
  REQUEST: 'FORM_CONTROL_STATUS.REQUEST',
  FAILURE: 'FORM_CONTROL_STATUS.FAILURE',
  SUCCESS: 'FORM_CONTROL_STATUS.SUCCESS',
  SUBMITTED: 'FORM_CONTROL_STATUS.SUBMITTED'
};

exports.default = FORM_CONTROL_STATUS;